<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ktdl-ui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KT.Downloader.Cli\KT.Downloader.Cli.csproj" />
  </ItemGroup>

</Project>
